### ISSUE TITLE
Please Add C++ syntax

### ISSUE THREAD

**Issue by rkhunter** [arcticicestudio/northem-light-atom-syntax#2]

**Comment by arcticicestudio** [comment]
I will try to implement it next weekend.

**Comment by arcticicestudio** [comment]
@rkhunter  Released new version [`0.11.0`](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v0.11.0) with implemented C++ support.
Would be nice to have some feedback or improvment suggestions.

**Comment by arcticicestudio** [comment]
Closing this since everything seems to be fine.
