### ISSUE TITLE
Support for Babel JSX

### ISSUE THREAD

**Issue by ghost** [arcticicestudio/northem-light-atom-syntax#3]
The only one light theme I can work, though sometimes I work with React (.JSX) files, and could use proper syntax highlighting.

**Comment by arcticicestudio** [comment]
Added <img src="https://facebook.github.io/react/favicon.ico" width=16 height=16/> [React.js](https://atom.io/packages/react) (`.jsx`) to the [backlog](https://github.com/arcticicestudio/northem-light-atom-syntax/issues/5).

**Comment by arcticicestudio** [comment]
Sorry for the long waiting period, but I've been busy on my job (one week SCRUM sprints are hectic :smile: ). I'll try to implement it this week, but no later than at the weekend.

**Comment by arcticicestudio** [comment]
@Pszek Could you post example code and describe the part where syntax highlighting is missing?
Tried some code from the official React JSX tutorial and for me everythings colored fine (since Atom detects JSX as a subtype of JavaScript). Only thing I've found was the missing coloring for HTML syntax code (like tag- and attribute names) returned in the `return()` function (this can be easily fixed by adding the `.source.js, .source.js.jsx` scopes to the HTML language file).

**Comment by ghost** [comment]
Thank You for Your effort. Here is the screenshot:

![synt](https://cloud.githubusercontent.com/assets/10253750/14395704/8189e18c-fdd3-11e5-8b76-85e48490df6b.jpg)

Generally it lacks colours for HTML tags and attributes.

**Comment by arcticicestudio** [comment]
Thanks, looks like something is not in sync with the other theme variations because `onClick` and closing- and opening tag brackets are not colored too (tested it in `northem-atom-syntax` yesterday and it worked fine).

**Comment by arcticicestudio** [comment]
@Pszek Here's a draft of the current changes:
- HTML tags and attributes are now inherit the syntax highlighting rules from the "html.less" stylesheet
- The JSX "embedded source" (`${dict[item]} ✗`) [syntax](https://facebook.github.io/jsx/#syntax) element `${}` and the embedded quote charater are now colored in `dark-blue` for better differation

![northem-light-atom-syntax-ghi-3-draft-1](https://cloud.githubusercontent.com/assets/7836623/14411226/2b29adfc-ff42-11e5-98f4-a54e24e64b7d.png)

I'd be happy for some feedback.

**Comment by ghost** [comment]
I like it! Could you update the source?

**Comment by arcticicestudio** [comment]
I'll push a new version as soon as I'm back from work, just waited for your response before merging it into the next release branch :smile:

**Comment by arcticicestudio** [comment]
:heavy_check_mark: I've released [`v0.18.0`](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v0.18.0).
This will close the backlog item <img src="https://facebook.github.io/react/favicon.ico" width=16 height=16/> [React.js](https://atom.io/packages/react) (`.jsx`).

**Comment by ghost** [comment]
Thanks, it works and I like it. Although a little bit more differentiation between dark and dark-grey could be useful.

PS. Will need to test it more at work, but waiting for the sun to show up first (cause this is the only time I use light themes).
