### ISSUE TITLE
Minimap git-diff

### ISSUE THREAD

**Issue by ghost** [arcticicestudio/northem-light-atom-syntax#4]
Current colours do not match the theme ones.
<img width="667" alt="screen shot 2016-03-25 at 10 40 55" src="https://cloud.githubusercontent.com/assets/10253750/14041985/1d5d28c6-f276-11e5-9743-e972a45741bb.png">

**Comment by arcticicestudio** [comment]
This is related to the fact that the theme currently does not support the [`minimap-git-diff`](https://atom.io/packages/minimap-git-diff) package.
I'll try to add it this evening for all theme variants.

**Comment by arcticicestudio** [comment]
Sorry for the long waiting period, but I've been busy on my job (one week SCRUM sprints are hectic :smile: ).
I've already implemented it, but it's not yet merged for the next release.
You can checkout the latest codebase to test it.
I'll merge it next weekend along with the support for #3 ([react](http://orktes.github.io/atom-react/) package)

**Comment by arcticicestudio** [comment]
:heavy_check_mark: Implemented support in [`v0.18.0`](https://github.com/arcticicestudio/northem-light-atom-syntax/releases/tag/v0.18.0).

**Comment by ghost** [comment]
Thanks it works, like it that the green and red are very light on the minimap.
