### ISSUE TITLE
Version 2.0.0

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-light-atom-syntax#8]
A backlog for the [Version 2.0.0](https://github.com/arcticicestudio/northem-light-atom-syntax/milestone/2) milestone.
The whole project will be cleaned up and rewritten to adapt the codebase of the [Nord Atom Syntax](https://github.com/arcticicestudio/nord-atom-ui) project.

All sub-issues are listed below and will be merged into the main milestone branch [`release/ghi-#8-2.0.0`](https://github.com/arcticicestudio/northem-light-atom-syntax/tree/release/ghi-%238-2.0.0).

  - [x] #9  Nord Atom Syntax codebase migration
  - [x] #10  Adapt new project setup and documentation style

**Detailed information about new features can be found in the [Nord Atom Syntax](https://github.com/arcticicestudio/nord-atom-ui#features) documentations!**

### Color Palette
This major update will migrate to the new Northem Light color palette version [`2.0.0`](https://github.com/arcticicestudio/northem-light/releases/tag/v2.0.0).

### Design
The current design is uncomfortable, unconsistent and has not been updated to the latest Atom version which results in unpredictable bugs and glitch due to changes of the Atom Core.
Northem Light Atom Syntax will adapt the Nord Atom Syntax design which provides a clean, elegant and up-to-date syntax highlighting.

### Language Support
All currently supported language packages will be migrated to the new codebase and packages currently supported by Nord Atom Syntax will be added.

### Documentation
All project documentations will adapt the new project setup and styles and new branding assets will be added.

**Comment by edwardloveall** [comment]
I think this syntax theme isn't so much for me. It's nice, but I prefer something with slightly bolder and more varied colors, so I don't have much feedback. The one thing I did notice while using it was when the cursor is over a parenthetical like `(` `)` or `[` `]` the outline makes the text a bit hard to read. I think base16 does it will with a small dotted underline instead of a whole box.

**Comment by arcticicestudio** [comment]
Thanks for your feedback, I also realized that the bracket matching box is nice in darker tinged themes, but on light backgrounds are hardly noticed.
I think I'll add a theme setting to allow the user to choose which type of match-marker should be used. I created the issue #11 for this improvement.
